### ISSUE TITLE
[Security] Algolia Keys Pushed to repo

### ISSUE THREAD

**Issue by rtcms** [E-Angadi/AngadiWeb#8]
Algolia Keys Pushed to repo ( Couldn't verify if they are working) for more info - https://github.com/streaak/keyhacks#Algolia-API-key

https://github.com/E-Angadi/AngadiWeb/blob/abf7ff1799acb49e7bce3d0e30a8f155d1932288/src/config/configs.js#L30
https://github.com/E-Angadi/AngadiWeb/blob/abf7ff1799acb49e7bce3d0e30a8f155d1932288/src/config/configs.js#L31

**Comment by tbharathchandra** [comment]
The real issue is Firebase hosting doesn't offer any environment variables that can configurable. Is there any way to hide this configs at least on GitHub as of now?

**Comment by rtcms** [comment]
I think this could be a possible solution?

https://stackoverflow.com/a/52043022

**Comment by tbharathchandra** [comment]
yeah this is one potential option, this involves placing a separate route to send those keys and subsequent async call (extra functions invocation ). If we don't get any other methods to solve this, let's go with this method.

**Comment by sadakchap** [comment]
Anyone working on this? If not... then Can I give it a try ?

**Comment by tbharathchandra** [comment]
Hey @sadakchap, Thank you for your interest towards AngadiWeb. You can try this. Before coding anything or coming up with any other solution, always try to think of reducing the number of Firebase function calls and also the number of docs to be queried to reduces Firebase billing.

Also post your solution here before coding, You can try the one we discussed above or any new one.

If you need any help, just post it here.

**Comment by sadakchap** [comment]
Thanks, I am searching about possible solutions.. and I'll let you know about various solution before coding. Thank you

**Comment by sadakchap** [comment]
Hi @tbharathchandra , thanks for patience.

As far as I have noticed, this project has config files at 2 places -
1. frontend (React)
2. firebase functions 

We can have config variables 2 ways- 
1. GCP Secret Manager - New one
2. [Firebase hosting config env](https://firebase.google.com/docs/functions/config-env)

The problem is both of them can be used from server-side NOT from client side.( I am assuming client app (react) is also hosted on firebase).

For client - we can just have a .env file, put variables there with `REACT_APP_` as prefix to all variable names, and on running `firebase deploy` it will also deploy env variables values correctly.

I have tried it by deploying a dummy react app to firebase [here](https://fir-react-614ff.web.app/).
Let me know what you think about it.

**Comment by tbharathchandra** [comment]
Hey @sadakchap, Great Job

You are correct, both of these are for server side configs

> 

    GCP Secret Manager - New one
    Firebase hosting config env

so, for the Firebase functions configs, we can use the second method, where we can deploy variables  by using a command like 

`firebase functions:config:set someservice.key="THE API KEY" someservice.id="THE CLIENT ID"
`

And coming to the method you suggested for client side, I think it good enough to scrap off the API keys from git. It is definitely better than what we have at this point of time.  

If you are interested make the required changes and raise a PR, also edit the readme file accordingly.

**Comment by sadakchap** [comment]
Hello @tbharathchandra , about updating readme, 
currently at step 8, we are setting up algolia and its keys in correct place. But now, we need to deploy algolia `app_id` and `admin key` to firebase.
For that, we first need to run `firebase init` (step 12) only after that we can deploy these keys. 

Should I move step 8 after step 12 or just update like this-

Create a Algolia account and create a index with name `products`(Case Sensitive). Generate the [API keys](https://www.algolia.com/doc/guides/security/api-keys/). Create a new file named `.env.local` in root directory and paste this -
```sh
  REACT_APP_ALGOLIA_APP_ID=app_id
  REACT_APP_ALGOLIA_SEARCH_ONLY_KEY=search_only_key
```
Copy the app_id and search only key and paste it in place of app_id & serach_only_key in file `.env.local`. After step 12, Copy the app id and admin key and replace your keys in the below command and run it. 
`firebase functions:config:set algolia.app_id="APP ID" algolia.admin_key="ADMIN KEY"`
Go through the steps in algolia, setup your search parameters as `title`, `description` such that, user can search over these two values only. You can adjust other search terms even after adding the products. Now your products data will be in sync with algolia data.

Please, let me know whether It will be good to move this step after we run `firebase init` or should I just edit the step 8?

**Comment by tbharathchandra** [comment]
Yeah you can move the steps as required, I don't have any reason to not rearrange them. also create a dummy txt file giving the format(field names) of .env file.

**Comment by sadakchap** [comment]
@tbharathchandra while editing readme, I just realized that we can do the same thing for razorpay keys, right now we are pushing dummy keys, but when using real keys they can be also pushed to the repo.
let me know if this also needs same change like the way we did for algolia keys.

**Comment by tbharathchandra** [comment]
They both are critical, they should be in env file

**Comment by sadakchap** [comment]
@tbharathchandra , I have made the following changes, please review them and let me know about it.

**Comment by tbharathchandra** [comment]
@sadakchap Thank you for your contributions. Please checkout other issues and hoping you will continue your contributions for Angadi Web. 

![All the best](https://media.tenor.com/images/b3ca7d23fee32fc541bce706bbf4d604/tenor.gif)
